---
title: "PNLS PMTCT Visualizations"
author: "Emily Linebarger"
date: "June 21, 2019"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(raster)
library(ggplot2)
library(ggrepel)
library(geosphere)
library(knitr)
library(tibble)
library(dplyr)
library(RColorBrewer)
library(rgdal)
library(rgeos)
library(rmarkdown)
library(maptools)
repo_root = "C:/Users/elineb/Documents/gf/" #Set to the root of your repository 
setwd(repo_root)
source('./core/standardizeDPSNames.R')

#Set up directories 
j = ifelse(Sys.info()[1]=='Windows', 'J:', '/home/j')
dir = paste0(j,  '/Project/Evaluation/GF/outcome_measurement/cod/dhis_data/prepped/pnls_final/') #Home directory
saveDir = paste0(j, 'Project/Evaluation/GF/outcome_measurement/cod/dhis_data/outputs/pnls/')
codeDir = paste0(repo_root, "outcome_measurement/all/cod/dhis/dhis_analysis/pnls_pmtct/")

source(paste0(codeDir, "pmtct_set_up_data.r"))
source(paste0(codeDir, "pmtct_plot_functions.r"))

```

# Reporting completeness
```{r echo=FALSE}
plot = gen_report1(dt, 7, unique(dt[element_no==7, .(element_eng)])
plot
```

# HIV+ pregnant and lactating women, by district


# HIV+ infants, by district 

# Map of HIV testing by DPS for PLW 

# Map of HIV testing by DPS for infants 

