---
title: "DRC 2019 Absorption"
author: "Emily Linebarger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, fig.dim=c(10, 7))

library(data.table) 
library(ggplot2)
library(knitr)
library(kableExtra)
library(Hmisc)
library(wesanderson)
library(gridExtra)
library(scales)

options(scipen=15)

save_loc = "J:/Project/Evaluation/GF/resource_tracking/visualizations/deliverables/_DRC 2019 annual report/"

dt = readRDS("C:/Users/elineb/Box Sync/Global Fund Files/COD/prepped_data/absorption_cod.rds")

#Assign each grant a distinct color from the "Zissou" palette. 
grants = unique(dt$grant) 
for (i in 1:length(grants)){
  g = grants[i]
  dt[grant==g, grant_color:=wes_palette("Zissou1")[i]]
}

#Add abbreviated module names. 
all_mods = readRDS("J:/Project/Evaluation/GF/resource_tracking/modular_framework_mapping/all_interventions.rds")
setnames(all_mods, c('module_eng', 'intervention_eng', 'abbrev_mod_eng', 'abbrev_int_eng'), c('gf_module', 'gf_intervention', 'abbrev_mod', 'abbrev_int'))
all_mods = all_mods[, .(gf_module, gf_intervention, disease, abbrev_mod, abbrev_int)]
dt = merge(dt, all_mods, by=c('gf_module', 'gf_intervention', 'disease'), allow.cartesian=TRUE)

#make sure this merge worked correctly. 
stopifnot(nrow(dt[is.na(abbrev_int)])==0)

#Subset the data
dt_current = dt[grant_period=="2018-2020"]
dt_current[, label:=paste0(round(absorption, 1), "%")]
dt_current[absorption>200, absorption:=200]

#Break out into smaller datasets. 
by_grant = dt_current[, .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('grant', 'grant_disease', 'start_date', 'semester', 'grant_color')]
by_grant[, absorption:=(expenditure/budget)*100]
by_grant[, label1:=paste0(round(absorption, 1), "%")]
by_grant[absorption>200, absorption:=200] # Cap absorption at 200%
by_grant[, label2:=paste0(grant_disease)]

by_module = dt_current[, .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('loc_name', 'grant', 'gf_module', 'abbrev_mod', 'start_date', 'semester', 'grant_color')]
by_module[, absorption:=(expenditure/budget)*100]
by_module[, label1:=paste0(round(absorption, 1), "%")]
by_module[absorption>200, absorption:=200] # Cap absorption at 200%
by_module[, label2:=dollar(expenditure)]

by_intervention = dt_current[, .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('loc_name', 'grant', 'gf_module', 'gf_intervention', 'abbrev_mod', 'abbrev_int', 'start_date', 'semester', 'grant_color')]
by_intervention[, absorption:=(expenditure/budget)*100]
by_intervention[, label1:=paste0(round(absorption, 1), "%")]
by_intervention[absorption>200, absorption:=200] # Cap absorption at 200%
```

# Overall absorption over time, by grant disease 
```{r absorption_by_disease} 

p1 = ggplot(by_grant, aes(x=semester, y=absorption, color=grant, group=grant)) + 
  geom_point() + 
  geom_line() + 
  theme_bw(base_size=16) + 
  labs(title="Absorption by grant for 2018-2020 grant period", x="Grant semester", y="Absorption (%)", color="Grant")

print(p1)
ggsave(paste0(save_loc, "absorption_over_time.png"), p1, height=8, width=10)
```

# Absorption over time, by grant

```{r absorption_over_time, results="asis"} 

by_module$semester <- factor(by_module$semester, levels=c('Semester 3', 'Semester 1-2', 'Semester 1'), labels=c('Semester 3', 'Semester 1-2', 'Semester 1'))
for (g in unique(by_module$grant)){
  subset = by_module[grant==g]
  
  p = ggplot(subset, aes(x=abbrev_mod, y=absorption, fill=semester, label=label1)) + 
    geom_bar(stat="identity", position="dodge") + 
    coord_flip() +
    theme_bw(base_size=16) + 
    geom_text( hjust=-0.5, position=position_dodge(width=1), size=4) + 
    labs(title=paste0("Absorption by semester and module \n for ", g), x="Module", y="Absorption (%)", fill="Grant semester")
  print(p)
  
  ggsave(paste0(save_loc, "absorption_for_", g, ".png"), p, height=8, width=12)
  
  cat("\n\n\\pagebreak\n")
}

```

# Compare absorption to historical average, by module 

```{r historical_compare}
historical_avg = dt[start_date!="2019-01-01", .(hist_budget=sum(budget, na.rm=T), hist_expenditure=sum(expenditure, na.rm=T)), by=c('abbrev_mod')]
historical_avg[, hist_absorption:=(hist_expenditure/hist_budget)*100]
historical_avg[hist_absorption>200, hist_absorption:=200]

only_2019 = dt[start_date=="2019-01-01", .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('abbrev_mod')]
only_2019[, absorption:=(expenditure/budget)*100]
only_2019[absorption>200, absorption:=200]

compare_2019 = merge(historical_avg, only_2019, by=c('abbrev_mod'))
compare_2019[, diff:=absorption-hist_absorption]

p = ggplot(compare_2019, aes(x=reorder(abbrev_mod, diff), y=diff, fill=diff)) + 
  geom_bar(stat="identity") + 
  theme_bw(base_size=16) + 
  coord_flip()+ 
  theme(legend.position="none") + 
  scale_fill_gradient2(low="red", high="green", midpoint=0, na.value="grey50") + 
  labs(title="2019 absorption, compared to historical average", x="Module", y="Difference between 2019 and historical absorption", 
       caption="*Historical absorption calculated since 2015")

ggsave(paste0(save_loc, "historical_absorption.png"), p, height=8, width=12)
```

```{r catalytic_funding} 

#Make a data table for this section that has cumulative funding since Jan. 2018 
dt_cumulative = dt_current[start_date>="2018-01-01", .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('abbrev_mod', 'abbrev_int', 'gf_module', 'gf_intervention')]
dt_cumulative[, absorption:=(expenditure/budget)*100]
dt_cumulative[, label:=paste0(round(absorption, 1), "%")]
dt_cumulative[absorption>200, absorption:=200]

dt_2019_wide = dt_current[start_date=="2019-01-01", .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('disease', 'gf_module', 'gf_intervention', 'abbrev_mod', 'abbrev_int')]
dt_2019_wide = melt(dt_2019_wide, id.vars=c('disease', 'gf_module', 'gf_intervention', 'abbrev_mod', 'abbrev_int'))
dt_2019_wide[variable=="budget", variable:="Budget"]
dt_2019_wide[variable=="expenditure", variable:="Expenditure"]
dt_2019_wide[variable=="Expenditure", label:=dollar(value)]
dt_2019_wide[is.na(label), label:=""]
dt_2019_wide[, value:=as.numeric(value)]

# HUMAN RIGHTS 
p = ggplot(dt_current[abbrev_mod=="Human rights barriers" & start_date=="2019-01-01"], aes(x=abbrev_int, y=absorption, fill=grant, label=label)) + 
  geom_bar(stat="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  facet_wrap(~grant) + 
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Human rights absorption for S1 2019", y="Absorption (%)", x="Intervention", fill="", caption="*Absorption capped at 200%")
  
ggsave(paste0(save_loc, "human_rights.png"), p, height=8, width=12)

p = ggplot(dt_cumulative[abbrev_mod=="Human rights barriers"], aes(x=abbrev_int, y=absorption,  label=label)) + 
  geom_bar(stat="identity", fill="goldenrod3") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Cumulative human rights absorption since Jan. 2018", y="Absorption (%)", x="Intervention", fill="", caption="*Absorption capped at 200%")
ggsave(paste0(save_loc, "human_rights_cumulative.png"), p, height=8, width=12)

p = ggplot(dt_2019_wide[abbrev_mod=="Human rights barriers"], aes(x=abbrev_int, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar, limits=c(0, 500000)) + 
  labs(title="Human rights budget/expenditure for S1 2019", y="", x="Intervention", fill="")
  
ggsave(paste0(save_loc, "human_rights_budget.png"), p, height=8, width=12)


# TB SCREENING/COMMUNITY OUTREACH 
tb_screening_ints = c('Case detection and diagnosis: MDR-TB', 'Community MDR-TB care delivery', 'Case detection and diagnosis', 'Community TB care delivery')
dt_current[abbrev_mod=="MDR-TB" & abbrev_int=="Case detection and diagnosis", abbrev_int:="MDR-TB: Case detection"]
dt_current[abbrev_mod=="MDR-TB" & abbrev_int=="Community care delivery", abbrev_int:="MDR-TB: Community care delivery"]
dt_current[abbrev_mod=="Care & prevention" & abbrev_int=="Case detection and diagnosis", abbrev_int:="TB: Case detection"]
dt_current[abbrev_mod=="Care & prevention" & abbrev_int=="Community TB care delivery", abbrev_int:="TB: Community care delivery"]

p = ggplot(dt_current[gf_intervention%in%tb_screening_ints & start_date=="2019-01-01"], aes(x=abbrev_int, y=absorption, fill=grant, label=label)) + 
  geom_bar(stat="identity") + 
  theme_bw(base_size=16) + 
  facet_wrap(~grant) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="TB screening/community care delivery \nfor S1 2019", y="Absorption (%)", x="Intervention", fill="", caption="*Absorption capped at 200%")

ggsave(paste0(save_loc, "tb_screening.png"), p, height=8, width=12)

dt_cumulative[abbrev_mod=="MDR-TB" & abbrev_int=="Case detection and diagnosis", abbrev_int:="MDR-TB: Case detection"]
dt_cumulative[abbrev_mod=="MDR-TB" & abbrev_int=="Community care delivery", abbrev_int:="MDR-TB: Community care delivery"]
dt_cumulative[abbrev_mod=="Care & prevention" & abbrev_int=="Case detection and diagnosis", abbrev_int:="TB: Case detection"]
dt_cumulative[abbrev_mod=="Care & prevention" & abbrev_int=="Community TB care delivery", abbrev_int:="TB: Community care delivery"]

p = ggplot(dt_cumulative[gf_intervention%in%tb_screening_ints], aes(x=abbrev_int, y=absorption,  label=label)) + 
  geom_bar(stat="identity", fill="goldenrod3") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Cumulative TB screening/community care delivery", y="Absorption (%)", x="Intervention", fill="", caption="*Absorption capped at 200%")

ggsave(paste0(save_loc, "tb_screening_cumulative.png"), p, height=8, width=12)

p = ggplot(dt_2019_wide[gf_intervention%in%tb_screening_ints], aes(x=abbrev_int, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="TB screening budget/expenditure for S1 2019", y="", x="Intervention", fill="", caption="*Absorption capped at 200%")
  
ggsave(paste0(save_loc, "tb_screening_budget.png"), p, height=8, width=12)

#RSSH / HMIS 
rssh = dt_current[disease=="rssh" & start_date=="2019-01-01", .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('abbrev_mod', 'abbrev_int')]
rssh[, absorption:=(expenditure/budget)*100]
rssh[, label:=paste0(round(absorption, 1), "%")]
rssh[absorption>200, absorption:=200]

rssh[, module_num:=.GRP, by='abbrev_mod']
rssh[, int_num:=.GRP, by=c('abbrev_mod', 'abbrev_int')]
rssh[, rssh_factor:=paste0(module_num, int_num)]
rssh$int_factor = factor(rssh$rssh_factor, unique(rssh$rssh_factor), unique(rssh$abbrev_int))
  
p = ggplot(rssh, aes(x=int_factor, y=absorption, label=label, fill=abbrev_mod)) + 
  geom_bar(stat="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="RSSH absorption for S1 2019", y="Absorption (%)", x="Module", caption="*Absorption capped at 200%", fill="")

ggsave(paste0(save_loc, "rssh.png"), p, height=8, width=12)

p = ggplot(dt_2019_wide[disease=="rssh"], aes(x=abbrev_int, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="RSSH budget/expenditure for S1 2019", y="", x="Intervention", fill="", caption="*Absorption capped at 200%")
  
ggsave(paste0(save_loc, "rssh_budget.png"), p, height=8, width=12)

#Historical investment in HMIS 
hmis = dt[abbrev_mod=="Info systems & M&E", .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('abbrev_mod', 'start_date')]
hmis[, absorption:=(expenditure/budget)*100]
hmis[, label:=paste0(round(absorption, 1), "%")]
hmis[absorption>200, absorption:=200]

p1 = ggplot(hmis, aes(x=start_date, y=budget, label=label)) + 
  geom_bar(stat="identity", fill="darkorchid3") + 
  theme_bw(base_size=16) + 
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="Investment in HMIS over time", x="Date", y="Budget")

p2 = ggplot(hmis, aes(x=start_date, y=absorption, label=label)) + 
  geom_point() + geom_line()+ 
  theme_bw(base_size=16) + 
  labs(title="Investment in HMIS over time", x="Date", y="Absorption (%)")

ggsave(paste0(save_loc, "hmis_budget.png"), p1, height=8, width=12)


  
```

```{r absorption_by_grant_disease} 
disease_cumulative = dt[start_date>="2018-01-01", .(budget=sum(budget, na.rm=T), expenditure=sum(expenditure, na.rm=T)), by=c('abbrev_mod', 'disease')]
disease_cumulative[, absorption:=(expenditure/budget)*100]
disease_cumulative[, label:=paste0(round(absorption, 1), "%")]
disease_cumulative[absorption>200, absorption:=200]

disease_cumulative_wide = disease_cumulative[, .(abbrev_mod, disease, budget, expenditure)]
disease_cumulative_wide = melt(disease_cumulative_wide, id.vars=c('disease', 'abbrev_mod'))
disease_cumulative_wide[variable=="budget", variable:="Budget"]
disease_cumulative_wide[variable=="expenditure", variable:="Expenditure"]
disease_cumulative_wide[variable=="Expenditure", label:=dollar(value)]
disease_cumulative_wide[is.na(label), label:=""]

#HIV 
p = ggplot(disease_cumulative[disease=="hiv"], aes(x=abbrev_mod, y=absorption, label=label)) + 
  geom_bar(stat="identity", fill="firebrick") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Absorption for HIV modules since Jan. 2018", y="Absorption (%)", x="Module", caption="*Absorption capped at 200%", fill="")

ggsave(paste0(save_loc, "hiv_modules.png"), p, height=8, width=12)

p = ggplot(disease_cumulative_wide[disease=="hiv"], 
           aes(x=abbrev_mod, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="Budget/Expenditure for HIV modules since Jan. 2018", y="", x="Module", fill="")

ggsave(paste0(save_loc, "hiv_modules_budget.png"), p, height=8, width=12)

p = ggplot(disease_cumulative[disease=="tb"], aes(x=abbrev_mod, y=absorption, label=label)) + 
  geom_bar(stat="identity", fill="dodgerblue") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Absorption for TB modules since Jan. 2018", y="Absorption (%)", x="Module", caption="*Absorption capped at 200%", fill="")

ggsave(paste0(save_loc, "tb_modules.png"), p, height=8, width=12)

p = ggplot(disease_cumulative_wide[disease=="tb"], 
           aes(x=abbrev_mod, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="Budget/Expenditure for TB modules since Jan. 2018", y="", x="Module", fill="")

ggsave(paste0(save_loc, "tb_modules_budget.png"), p, height=8, width=12)

p = ggplot(disease_cumulative[disease=="malaria"], aes(x=abbrev_mod, y=absorption, label=label)) + 
  geom_bar(stat="identity", fill="goldenrod3") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Absorption for malaria modules since Jan. 2018", y="Absorption (%)", x="Module", caption="*Absorption capped at 200%", fill="")

ggsave(paste0(save_loc, "mal_modules.png"), p, height=8, width=12)

p = ggplot(disease_cumulative_wide[disease=="malaria"], 
           aes(x=abbrev_mod, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="Budget/Expenditure for malaria modules since Jan. 2018", y="", x="Module", fill="")

ggsave(paste0(save_loc, "mal_modules_budget.png"), p, height=8, width=12)

p = ggplot(disease_cumulative[disease=="rssh"], aes(x=abbrev_mod, y=absorption, label=label)) + 
  geom_bar(stat="identity", fill="purple") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(limits=c(0, 250)) + 
  labs(title="Absorption for RSSH modules since Jan. 2018", y="Absorption (%)", x="Module", caption="*Absorption capped at 200%", fill="")

ggsave(paste0(save_loc, "rssh_modules.png"), p, height=8, width=12)

p = ggplot(disease_cumulative_wide[disease=="rssh"], 
           aes(x=abbrev_mod, y=value, fill=variable, label=label)) + 
  geom_bar(stat="identity", position="identity") + 
  theme_bw(base_size=16) + 
  geom_text(hjust=0) + 
  coord_flip() +
  scale_y_continuous(labels=scales::dollar) + 
  labs(title="Budget/Expenditure for RSSH modules since Jan. 2018", y="", x="Module", fill="")

ggsave(paste0(save_loc, "rssh_modules_budget.png"), p, height=8, width=12)


``` 